### ISSUE TITLE
tetr_bot strange behaviour.

### ISSUE THREAD

**Issue by BatsLog** [wenlianglaw/Tetris-in-Python#2]
I don't know if this is the right way to use "Issues" since it is my first time writing it.

Maybe it is about something I miss but tetr_bot on Zen mode makes one move REAL quickly and then goes on a hiatus for a few hands and then randomly makes another 1-2 moves and the same story repeats. (Could only run in the Debug/RwithoutDbug mode due to lack of my abilities; under VS Code). The terminal spitting lines 45-50ms decimals.

Also, init_my_configuration tells you to click on places contradicting order with read_me. Which, readme has the right information.

I unfortunately never got to make the "main.py" work despite trying everything.

**Comment by wenlianglaw** [comment]
sorry I was not watching the issue list... looking now...

**Comment by wenlianglaw** [comment]
I think I'm probably going to stop the tetr.io feature.

I didn't spend too much time on this repository now...  And I'm focus on some other things.
